# Generated by Django 5.2.3 on 2025-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('codigo_postal', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('jurídico', 'Jurídico'), ('natural', 'Natural')], max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=70)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'editor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_edit', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_conect', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('born', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('registro', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('turistica', 'Turistica'), ('oseo', 'Oseo'), ('educativa', 'Educativa'), ('salud', 'Salud')], max_length=100)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gerente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('tema', models.CharField(blank=True, max_length=30, null=True)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salon', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('convencional', 'Convencional'), ('bajo demanda', 'Bajo demanda')], max_length=100)),
            ],
            options={
                'db_table': 'salon',
                'managed': False,
            },
        ),
    ]
